version: "3"

services:
  vote:
    build: ./select
    command: python app.py
    ports:
      - "5000:80"
    networks:
      - front-end
      - back-end

  result:
    build: ./result
    command: nodemon --debug server.js
    ports:
      - "5001:80"
      - "5858:5858"
    networks:
      - front-end
      - back-end

  worker:
    build:
      context: ./worker
    networks:
      - back-end

  redis:
    image: redis
    container_name: redis
    ports: ["6379"]
    networks:
      - back-end

  db:
    image: postgres:9.4
    container_name: db
    networks:
      - back-end

networks:
  front-end:
  back-end:
